### ISSUE TITLE
WooCommerce and Mautic integration plugin - problem with customer tracking

### ISSUE THREAD

**Issue by dhmusman** [mautic/api-library#111]
Hi guys,

I am developing an integration between woocommerce and Mautic. This integration will create new contacts when a customer place an order, as well as sync previous woocommerce customers to Mautic. This plugin also allows to set product name, product SKU and order status as tags.

Everything is working so far except for tracking. Meaning, web activity of contacts are not being detected. This plugin also sends the contact IP, which I though it would enable precious web tracking (by merging the previous collected tracking from the IP to the newly created contact). However, this is not the case.

I checked and I realized that the unidentified and identified contacts have the same IP ID, then the question is does the system not automatically merge these two? When I send the contact from WooCommerce through the API, do I need to check if the IP already exist, and if it does use that unidentified contact ID to populate the contact fields?

**Comment by escopecz** [comment]
Hi,

Mautic do not use IP as an identifier. It was removed because for example one class of students accessing Mautic would be considered as 1 contact.

The only default identifier is either ID or email address. Automatic merging contacts by email address via API has been added to Mautic recently.

Take a look at https://github.com/escopecz/mautic-form-submit. Maybe you will find some inspiration there.

**Comment by dhmusman** [comment]
Thanks for reply...
