### ISSUE TITLE
I want to use api library at the same time in two different plugin.

### ISSUE THREAD

**Issue by dhmusman** [mautic/api-library#114]
Please help me to resolve. 
PHP Fatal error:  Cannot declare interface Psr\Log\LoggerAwareInterface, because the name is already in use in path\mautic\Psr\Log\LoggerAwareInterface.php on line 8

**Comment by escopecz** [comment]
Please provide more info.

**Comment by dhmusman** [comment]
I have make one wordpress plugin which is creating the contacts when some make order on site, Now my client want to use [Ninaj Popup plugin](https://codecanyon.net/item/ninja-popups-for-wordpress/3476479?ref=hafizusman) but when I active the both plugin I am facing the issue 

> Cannot declare interface Psr\Log\LoggerAwareInterface, because the name is already in use 
Sorry for bad English..

**Comment by escopecz** [comment]
Your English is wonderful!

I see, so it's about WP plugins. I think that the guys in the official Mautic-WP plugin are on to something: https://github.com/mautic/mautic-wordpress/issues/62

I don't know how to fix it in WP. It's easy in a modern PHP app using Composer - just load the library once, use it wherever you want. I'll close this issue. Please move the discussion to the issue I linked.

**Comment by Jackvashu** [comment]
hey there : 

I started creating new plugins with existing plugins using twilio api but I am getting error 

In MauticHelloWorldBundle.php line 21:

  Compile Error: Cannot declare class Mautic\HelloWorldBundle\MauticHelloWorldBundle, because the name is already in
  use


cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>


kindly help me I am stuck since last week

**Comment by escopecz** [comment]
The error states that you have 2 classes with the same name and namespace:

```
Mautic\HelloWorldBundle\MauticHelloWorldBundle
```

It's not related with this GitHub repository though. Ask your future questions in https://github.com/mautic/plugin-helloworld or maybe in the Mautic community Slack where you can get faster responses.
