### ISSUE TITLE
Release a stable version

### ISSUE THREAD

**Issue by iadj** [mautic/api-library#57]
I've been using this API in production for automatically signing users up to the mailing list. With sudden deprecations and such, Mautic cannot be a viable option if the API keeps breaking.

Please release a stable version.

**Comment by escopecz** [comment]
Please let us know what is broken.

**Comment by iadj** [comment]
What I mean is deprecating the functionality of the API breaks the code of projects that implement it.

Mautic 2.0 needs a stable API, to create contacts and add them to segments, that doesn't break project code when there's an update.

**Comment by iadj** [comment]
@alanhartless Don't get me wrong, I love Mautic! I just got worried that the API might renew again and deprecate some functions. "newApi" just doesn't seem like a long-term api context name.

**Comment by iadj** [comment]
Maybe versioning would be a good start i.e. 0.1.0 etc. so any code breaking release can be a new version i.e. 0.2.0?

**Comment by alanhartless** [comment]
If referring to this repo, we are. See tags/releases. They are currently in sync with Mautic version changes. 

Thanks!

Alan

On Sat, Aug 27, 2016 at 16:35 iadj

<
mailto:iadj <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Maybe versioning would be a good start i.e. 0.1.0 etc. so any code breaking release can be a new version i.e. 0.2.0?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/mautic/api-library/issues/57#issuecomment-242942170
, or
