### ISSUE TITLE
Segments class does not contain method getSegments

### ISSUE THREAD

**Issue by pavel-janicek** [mautic/api-library#68]
From the [documentation](https://developer.mautic.org/#segments):

To get all segments:
```
<?php
use Mautic\MauticApi;
use Mautic\Auth\ApiAuth;

// ...
$auth     = ApiAuth::initiate($settings);
$apiUrl   = "https://your-mautic.com"; 
$segmentApi = MauticApi::getContext("segments", $auth, $apiUrl);

//...
$segments = $segmentApi->getSegments();
```

However, if you look at [Segments ](https://github.com/mautic/api-library/blob/master/lib/Api/Segments.php) class, the file does not contain method `getSegments()`

The method is specified in [Leads](https://github.com/mautic/api-library/blob/master/lib/Api/Leads.php) class as `getLists()`

So, correct way to get all segments is this:
```
<?php
use Mautic\MauticApi;
use Mautic\Auth\ApiAuth;

// ...
$auth     = ApiAuth::initiate($settings);
$apiUrl   = "https://your-mautic.com"; 
$segmentApi = MauticApi::getContext("leads", $auth, $apiUrl);
//...
$segments = $segmentApi->getLists();
```

**Comment by escopecz** [comment]
Hi Pavel! I think that this issue was introduced when renaming "list" to "segment" by find-replace operation. The API will get a major feature update soon. Here is new unit test for it where the use is shown: https://github.com/escopecz/api-library/blob/write-endpoints/tests/Api/SegmentsTest.php#L28

The developer documentation is at this repo if you'd like to fix similar glitches yourself in the future: https://github.com/mautic/developer-documentation/blob/master/source/includes/_api_endpoint_segments.md

But this one is already fixed here: https://github.com/mautic/developer-documentation/pull/31/files#diff-c3dfe6ff6ffb4e3d7ded8c14c1196a6aR83
